name: "Build"

on:
  workflow_run:
    workflows:
      - "Update"
      - "Update Flake"
    types:
      - "completed"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: stepbrobd
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build
