name: Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: experimental-features = nix-command flakes
      - name: "Update"
        run: ./update.sh
      - name: Commit and Push
        if: ${{ env.PUSH== 'true' }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global push.followTags true
          git add update.sh ./systems
          git commit -m "GitHub Action: osu! version update: ${{ env.TAG }}"
          git push
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}
